import type { VehicleType } from "../types/vehicle";

export type VehicleSetupSection =
  | "riding"
  | "tyres"
  | "tube-system"
  | "suspension"
  | "gearing"
  | "controls"
  | "protection"
  | "cooling"
  | "fuel"
  | "navigation"
  | "tools"
  | "luggage"
  | "comfort"
  | "electronics"
  | "winch-recovery"
  | "cargo"
  | "lighting"
  | "comms"
  | "roof-doors"
  | "drivetrain"
  | "snorkel"
  | "camping"
  | "power"
  | "custom";

export type UsageTrackingMode = "hours" | "mileage" | "both";

export type VehicleSetupConfig = {
  label: string;
  usageTrackingMode: UsageTrackingMode;
  setupSections: VehicleSetupSection[];
  ridingSetupOptions: string[];
  tyreTypeOptions: string[];
  suspensionOptions: string[];
  protectionOptions: string[];
  recoveryOptions: string[];
  fuelOptions: string[];
  navigationOptions: string[];
  lightingOptions: string[];
  toolsAndSparesOptions: string[];
  drivetrainOptions: string[];
  lockerOptions: string[];
};

export const vehicleSetupConfig: Record<VehicleType, VehicleSetupConfig> = {
  "dirt-bike": {
    label: "Dirt Bike",
    usageTrackingMode: "hours",
    setupSections: [
      "riding",
      "tyres",
      "tube-system",
      "suspension",
      "gearing",
      "controls",
      "protection",
      "lighting",
      "cooling",
      "fuel",
      "navigation",
      "tools",
      "custom",
    ],
    ridingSetupOptions: [
      "Hard Enduro",
      "Light Enduro",
      "Motocross",
      "Sand",
      "Forest",
      "Rocks",
      "General Trail",
      "Custom",
    ],
    tyreTypeOptions: [
      "Soft",
      "Medium",
      "Hard",
      "Sand",
      "Mud",
      "Hybrid",
      "Custom",
    ],
    suspensionOptions: [
      "Soft",
      "Standard",
      "Firm",
      "Motocross",
      "Enduro",
      "Sand",
      "Rocks",
      "Custom",
    ],
    protectionOptions: [
      "Skid plate",
      "Hand guards",
      "Pipe guard",
      "Radiator braces",
      "Disc guards",
      "Frame guards",
      "Clutch cover guard",
      "Custom",
    ],
    recoveryOptions: ["Tow strap", "Trail rope", "Custom"],
    fuelOptions: [
      "Stock tank",
      "Long range tank",
      "Aux fuel bottle",
      "Premix setup",
      "Custom",
    ],
    navigationOptions: [
      "Phone mount",
      "GPS unit",
      "Offline maps",
      "Roadbook",
      "Custom",
    ],
    lightingOptions: [
      "Stock headlight",
      "LED headlight",
      "Enduro headlight",
      "Aux light",
      "Tail light",
      "Headlight delete",
      "Custom",
    ],
    toolsAndSparesOptions: [
      "Trail tools",
      "Spare tube",
      "Tyre levers",
      "Pump",
      "Plug kit",
      "Tow strap",
      "Spark plug",
      "Custom",
    ],
    drivetrainOptions: [
      "Standard chain drive",
      "Technical gearing",
      "High-speed gearing",
      "Custom",
    ],
    lockerOptions: ["Not applicable"],
  },

  "adventure-bike": {
    label: "Adventure Bike",
    usageTrackingMode: "both",
    setupSections: [
      "riding",
      "tyres",
      "suspension",
      "gearing",
      "luggage",
      "navigation",
      "lighting",
      "protection",
      "comfort",
      "electronics",
      "fuel",
      "tools",
      "custom",
    ],
    ridingSetupOptions: [
      "Adventure",
      "Dual Sport",
      "Touring",
      "Gravel Roads",
      "Light Enduro",
      "General Trail",
      "Custom",
    ],
    tyreTypeOptions: [
      "Road Biased",
      "70/30",
      "50/50",
      "40/60",
      "Knobby",
      "Sand",
      "Mud",
      "Custom",
    ],
    suspensionOptions: [
      "Comfort",
      "Standard",
      "Firm",
      "Loaded luggage",
      "Off-road",
      "Touring",
      "Custom",
    ],
    protectionOptions: [
      "Crash bars",
      "Skid plate",
      "Hand guards",
      "Radiator guard",
      "Headlight guard",
      "Engine guards",
      "Custom",
    ],
    recoveryOptions: ["Tow strap", "Recovery rope", "Custom"],
    fuelOptions: [
      "Stock tank",
      "Long range tank",
      "Aux fuel bottle",
      "Fuel bladder",
      "Custom",
    ],
    navigationOptions: [
      "Phone mount",
      "GPS unit",
      "Roadbook",
      "Offline maps",
      "USB charger",
      "Custom",
    ],
    lightingOptions: [
      "Stock lights",
      "Aux lights",
      "Fog lights",
      "Spot lights",
      "Light bar",
      "Highway touring lights",
      "Custom",
    ],
    toolsAndSparesOptions: [
      "Tyre repair kit",
      "Compressor",
      "Chain lube",
      "Basic tools",
      "Tow strap",
      "Spare tube",
      "Custom",
    ],
    drivetrainOptions: [
      "Standard gearing",
      "Off-road gearing",
      "Touring gearing",
      "Loaded travel gearing",
      "Custom",
    ],
    lockerOptions: ["Not applicable"],
  },

  quad: {
    label: "Quad",
    usageTrackingMode: "hours",
    setupSections: [
      "riding",
      "tyres",
      "suspension",
      "drivetrain",
      "protection",
      "winch-recovery",
      "cargo",
      "lighting",
      "navigation",
      "fuel",
      "tools",
      "custom",
    ],
    ridingSetupOptions: [
      "Trail",
      "Mud",
      "Sand",
      "Utility",
      "Racing",
      "Farm",
      "Hunting",
      "General Trail",
      "Custom",
    ],
    tyreTypeOptions: [
      "Trail",
      "Mud",
      "Sand",
      "All Terrain",
      "Utility",
      "Racing",
      "Custom",
    ],
    suspensionOptions: [
      "Soft",
      "Standard",
      "Firm",
      "Utility",
      "Racing",
      "Mud setup",
      "Custom",
    ],
    protectionOptions: [
      "Skid plates",
      "A-arm guards",
      "Bumper",
      "Hand guards",
      "Nerf bars",
      "Frame guards",
      "Custom",
    ],
    recoveryOptions: [
      "Winch",
      "Tow strap",
      "Recovery rope",
      "Snatch block",
      "Anchor",
      "Custom",
    ],
    fuelOptions: ["Stock tank", "Aux fuel", "Long range setup", "Custom"],
    navigationOptions: ["Phone mount", "GPS unit", "Offline maps", "Custom"],
    lightingOptions: [
      "LED bar",
      "Spot lights",
      "Work lights",
      "Rear light",
      "Trail lights",
      "Custom",
    ],
    toolsAndSparesOptions: [
      "Plug kit",
      "Compressor",
      "Tow strap",
      "Basic tools",
      "Spare belt",
      "Custom",
    ],
    drivetrainOptions: [
      "2WD",
      "4WD",
      "Selectable 4WD",
      "Low range",
      "Utility setup",
      "Racing setup",
      "Custom",
    ],
    lockerOptions: [
      "Open diff",
      "Limited slip",
      "Selectable diff lock",
      "No locker",
      "Custom",
    ],
  },

  sxs: {
    label: "SXS",
    usageTrackingMode: "hours",
    setupSections: [
      "riding",
      "tyres",
      "suspension",
      "drivetrain",
      "winch-recovery",
      "protection",
      "lighting",
      "comms",
      "roof-doors",
      "cargo",
      "navigation",
      "fuel",
      "tools",
      "custom",
    ],
    ridingSetupOptions: [
      "Trail",
      "Rock crawling",
      "Mud",
      "Sand",
      "Racing",
      "Utility",
      "Overlanding",
      "General Trail",
      "Custom",
    ],
    tyreTypeOptions: [
      "All Terrain",
      "Mud Terrain",
      "Sand",
      "Rock",
      "Racing",
      "Utility",
      "Custom",
    ],
    suspensionOptions: [
      "Comfort",
      "Sport",
      "Rock setup",
      "Sand setup",
      "Heavy load",
      "Custom",
    ],
    protectionOptions: [
      "Skid plates",
      "Rock sliders",
      "A-arm guards",
      "Bumpers",
      "Trailing arm guards",
      "Custom",
    ],
    recoveryOptions: [
      "Winch",
      "Recovery rope",
      "Soft shackles",
      "Snatch block",
      "Tree saver",
      "Tow points",
      "Custom",
    ],
    fuelOptions: ["Stock tank", "Aux fuel", "Long range setup", "Custom"],
    navigationOptions: [
      "GPS",
      "Tablet mount",
      "Phone mount",
      "Offline maps",
      "Custom",
    ],
    lightingOptions: [
      "Light bar",
      "Rock lights",
      "Pod lights",
      "Rear chase light",
      "Work lights",
      "Whip lights",
      "Custom",
    ],
    toolsAndSparesOptions: [
      "Spare belt",
      "Plug kit",
      "Compressor",
      "Jack",
      "Basic tools",
      "Spare axle",
      "Custom",
    ],
    drivetrainOptions: [
      "2WD",
      "4WD",
      "Low range",
      "Clutch kit",
      "Rock crawling setup",
      "Sand setup",
      "Racing setup",
      "Custom",
    ],
    lockerOptions: [
      "Open diff",
      "Rear locker",
      "Front locker",
      "Selectable locker",
      "No locker",
      "Custom",
    ],
  },

  "4x4": {
    label: "4x4",
    usageTrackingMode: "mileage",
    setupSections: [
      "riding",
      "tyres",
      "suspension",
      "drivetrain",
      "winch-recovery",
      "protection",
      "lighting",
      "snorkel",
      "camping",
      "navigation",
      "power",
      "fuel",
      "tools",
      "custom",
    ],
    ridingSetupOptions: [
      "Overlanding",
      "Rock crawling",
      "Mud",
      "Sand",
      "Touring",
      "Trail driving",
      "Recovery support",
      "General 4x4",
      "Custom",
    ],
    tyreTypeOptions: [
      "All Terrain",
      "Mud Terrain",
      "Rock Terrain",
      "Sand",
      "Highway Terrain",
      "Hybrid",
      "Custom",
    ],
    suspensionOptions: [
      "Stock",
      "2 inch lift",
      "3 inch lift",
      "Long travel",
      "Heavy load",
      "Comfort touring",
      "Custom",
    ],
    protectionOptions: [
      "Bull bar",
      "Rock sliders",
      "Skid plates",
      "Diff guards",
      "Bash plates",
      "Rear bumper",
      "Underbody protection",
      "Custom",
    ],
    recoveryOptions: [
      "Winch",
      "Recovery boards",
      "Kinetic rope",
      "Tow strap",
      "Soft shackles",
      "Snatch block",
      "Hi-lift jack",
      "Air compressor",
      "Custom",
    ],
    fuelOptions: [
      "Stock tank",
      "Long range tank",
      "Jerry cans",
      "Fuel range estimate",
      "Custom",
    ],
    navigationOptions: [
      "GPS",
      "Tablet",
      "Offline maps",
      "Radio comms",
      "Satellite messenger",
      "Custom",
    ],
    lightingOptions: [
      "Light bar",
      "Spot lights",
      "Fog lights",
      "Rock lights",
      "Camp lights",
      "Rear work light",
      "Custom",
    ],
    toolsAndSparesOptions: [
      "Full tool kit",
      "Tyre repair kit",
      "Compressor",
      "Spare fluids",
      "Jack",
      "Recovery kit",
      "Custom",
    ],
    drivetrainOptions: [
      "Open diffs",
      "Rear locker",
      "Front and rear lockers",
      "Center diff lock",
      "Limited slip",
      "Low range",
      "Regeared",
      "Custom",
    ],
    lockerOptions: [
      "No lockers",
      "Rear locker",
      "Front locker",
      "Front and rear lockers",
      "Center diff lock",
      "Limited slip",
      "Custom",
    ],
  },

  other: {
    label: "Other",
    usageTrackingMode: "both",
    setupSections: [
      "riding",
      "tyres",
      "suspension",
      "drivetrain",
      "fuel",
      "protection",
      "navigation",
      "tools",
      "custom",
    ],
    ridingSetupOptions: [
      "General Trail",
      "Utility",
      "Adventure",
      "Touring",
      "Custom",
    ],
    tyreTypeOptions: [
      "All Terrain",
      "Mud",
      "Sand",
      "Road Biased",
      "Utility",
      "Custom",
    ],
    suspensionOptions: ["Soft", "Standard", "Firm", "Custom"],
    protectionOptions: ["Basic protection", "Heavy duty protection", "Custom"],
    recoveryOptions: ["Tow strap", "Recovery rope", "Winch", "Custom"],
    fuelOptions: ["Stock tank", "Aux fuel", "Custom"],
    navigationOptions: ["Phone mount", "GPS", "Offline maps", "Custom"],
    lightingOptions: [
      "Stock lights",
      "Aux lights",
      "Work lights",
      "Trail lights",
      "Custom",
    ],
    toolsAndSparesOptions: ["Basic tools", "Tyre kit", "Compressor", "Custom"],
    drivetrainOptions: [
      "Standard",
      "Trail setup",
      "Utility setup",
      "Custom",
    ],
    lockerOptions: [
      "Not applicable",
      "Open diff",
      "Limited slip",
      "Locker",
      "Custom",
    ],
  },
};

export function getVehicleSetupConfig(type?: VehicleType | "") {
  if (!type) return vehicleSetupConfig.other;
  return vehicleSetupConfig[type] ?? vehicleSetupConfig.other;
}